name = "Void"
license = "MIT"
licenselink = "https://github.com/pseudosma/void/blob/master/LICENSE"
description = "A dark, dystopian theme for writers"
homepage = "https://github.com/pseudosma/void"
tags = ["analog", "animated", "black", "clean", "dark", "digital", "glitch", "horror", "scary", "text", "video", "void"]
features = ["accessibility", "chapters", "clean", "mobile", "randomization"]

[author]
  name = "David Paige"
  homepage = "https://github.com/pseudosma/void"
